# Generated by Django 5.0.6 on 2025-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttandanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.CharField(choices=[('ADA', 'ADA'), ('CN', 'CN'), ('WD', 'WD'), ('IPDC', 'IPDC'), ('PE', 'PE'), ('DE', 'DE')], max_length=10)),
                ('faculty', models.CharField(choices=[('SJA', 'SJA'), ('HHM', 'HHM'), ('PMC', 'PMC'), ('CHM', 'CHM'), ('NSS', 'NSS'), ('NBN', 'NBN'), ('DDS', 'DDS'), ('BKB', 'BKB')], max_length=10)),
                ('lecture_notes', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('enrollment', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
