# Generated by Django 5.0.6 on 2025-07-16 19:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AttandanceData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandancedata',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
