# Generated by Django 5.0.6 on 2025-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttandanceData', '0002_alter_attandancedata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attandancedata',
            name='file',
            field=models.CharField(max_length=200),
        ),
    ]
